config/routes.rb
Rails.application.routes.draw do
  get 'orders/express'
  get 'line_items/create'
  get 'carts/show'

  resources :orders
  resources :products
  resources :categories

  root 'products#index'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items
  has_one :order
  
  def total_price
    # convert to array so it doesn't try to do sum on database directly
    line_items.to_a.sum(&:full_price)
  end
    
end


 

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :cart
  belongs_to :product
  
  def full_price
    unit_price * quantity
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :cart
  has_many :payments
  
  serialize :details
  
  def price_in_cents
    (cart.total_price*100).round
  end
      
end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :order
  serialize :details
  
  def response=(response)
    self.success       = response.success?
    self.authorization = response.authorization
    self.message       = response.message
    self.details       = response.params
  rescue ActiveMerchant::ActiveMerchantError => e
    self.success       = false
    self.authorization = nil
    self.message       = e.message
    self.details       = {}
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  def current_cart
    if session[:cart_id]
      @current_cart ||= Cart.find(session[:cart_id])
    end
    if session[:cart_id].nil?
      @current_cart = Cart.create!
      session[:cart_id] = @current_cart.id
    end
    @current_cart
  end
  
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @cart = current_cart
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  def create
    @product = Product.find(params[:product_id])
    @line_item = LineItem.create!(cart: current_cart, 
                                  product: @product, 
                                  quantity: 1, 
                                  unit_price: @product.price)
        
    redirect_to carts_show_url
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  include Yukon
  # Step 1 : SetExpressCheckout
  def express
    # price (in cents), buyer_ip, return_url, cancel_return_url, notify_url (optional)
    @payment_processor = PaymentProcessor.new('sell_1342421142_biz@gmail.com')
    response = @payment_processor.set_express_checkout(current_cart.build_order.price_in_cents,
                                                     request.remote_ip,
                                                     new_order_url,
                                                     products_url,
                                                     'bugs')
                                                     
    # Redirect to Paypal URL : args - response
    redirect_to @payment_processor.redirect_url_for(response)
  end
  
  # This is the return_url. After Paypal interaction this is executed.
  def new
    @order = current_cart.build_order
    # Step 2 : GetExpressCheckoutDetails  : args - token
    @payment_processor = PaymentProcessor.new('sell_1342421142_biz@gmail.com')
    details = @payment_processor.get_express_checkout_details(params[:token])
    @order.details = details.params
    @order.ip_address = request.remote_ip

    if @order.save
      # Step 3 : DoExpressCheckoutPayment
      response = @payment_processor.do_express_checkout_payment(@order.price_in_cents, 
                                                                request.remote_ip,
                                                                params[:token],
                                                                params[:PayerID])
      
      if response.success?
        @order.payments.create!(action: "purchase", amount: @order.price_in_cents, response: response)
        # Checkout complete. 
        clear_cart_session
        
        render action: "success"
      else
        render action: "failure"
      end
    else
      render action: 'new'
    end
  end

  private
    
  def clear_cart_session
    session[:cart_id] = nil
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/carts/purchase.html.erb
 <h1>Purchase Successful</h1>

<p><strong>Thank you for your order!</strong> We will process it within one business day.</p>
<p><%= link_to "Back to Products", products_path %></p>

app/views/carts/show.html.erb
<h1>Shopping Cart</h1>

<table id="line_items">
  <tr>
    <th>Product</th>
    <th>Qty</th>
    <th class="price">Unit Price</th>
    <th class="price">Full Price</th>
  </tr>
  <% for line_item in @cart.line_items %>
    <tr class="<%= cycle :odd, :even %>">
      <td><%=h line_item.product.name %></td>
      <td class="qty"><%= line_item.quantity %></td>
      <td class="price"><%= number_to_currency(line_item.unit_price) %></td>
      <td class="price"><%= number_to_currency(line_item.full_price) %></td>
    </tr>
  <% end %>
  <tr>
    <td class="total price" colspan="4">
      Total: <%= number_to_currency @cart.total_price %>
    </td>
  </tr>
</table>

<p>
  <%= link_to image_tag("https://www.paypal.com/en_US/i/btn/btn_xpressCheckout.gif"), orders_express_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ppexp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/orders/failure.html.erb
FAILURE

app/views/orders/success.html.erb
SUCCESS!
<br/>
You just bought : <%= @order.cart.line_items.first.product.name %> <br/>
Total Amount Charged : <%= @order.details['order_total'] %><br/>

Confirmation email has been sent to : <%= @order.details['payer'] %>. <br/>
Please add notifications@example.com to your spam filter to avoid the confirmation email from being blocked.

app/views/products/index.html.erb
<% for product in @products %>
  <div class="product">
    <h3>
      <%= product.name %>
      <%= number_to_currency(product.price) %>
    </h3>
    <div class="actions">
      <%= link_to "Add to Cart", line_items_create_path(:product_id => product) %>
    </div>
  </div>
<% end %>